### ISSUE TITLE
This error pops up when we use `$./generate.sh stateTransition` to generate proofs

### ISSUE THREAD

**Issue by jjhbk** [0xPolygonID/tutorial-examples#12]
/home/jjhbk/coding/polygonid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:149
		throw new Error(`Too many values for input signal ${k}\n`);
		      ^

Error: Too many values for input signal authClaimMtp

    at /home/jjhbk/coding/polygonid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:149:9
    at Array.forEach (<anonymous>)
    at WitnessCalculator._doCalculateWitness (/home/jjhbk/coding/polygonid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:136:14)
    at WitnessCalculator.calculateWTNSBin (/home/jjhbk/coding/polygonid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/witness_calculator.js:212:20)
    at /home/jjhbk/coding/polygonid/tutorial-examples/compiled-circuits/stateTransition/stateTransition_js/generate_witness.js:15:38

Input file is:
{
  "authClaim": [
    "80551937543569765027552589160822318028",
    "0",
    "10433634480315839738859604482207101502928152626802053238287459543904614636561",
    "19938786944276154655734737680705087349230601300848199702835439274416502769538",
    "1",
    "0",
    "0",
    "0"
  ],
  "authClaimMtp": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "authClaimNonRevMtp": [
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "authClaimNonRevMtpAuxHi": "0",
  "authClaimNonRevMtpAuxHv": "0",
  "authClaimNonRevMtpNoAux": "1",
  "userID": "23935469294320920479531036849908063866980806990252357589148608365407830016",
  "newUserState": "3377081614773277995446610810613301548025798411006285296955069293227344717042",
  "oldUserState": "3572937177090474971607924737503202991959909332221693546557306412339729645189",
  "isOldStateGenesis": "1",
  "claimsTreeRoot": "18739890053350260705887303701748077859055891329240947128791199976561719860651",
  "revTreeRoot": "0",
  "rootsTreeRoot": "0",
  "signatureR8x": "3958530599092387886523601168434167478508379841202053483610517485992253423872",
  "signatureR8y": "11271104850483952572109633311171159497582279800016048066451804024472158880909",
  "signatureS": "2365263433123484748941997476995424494692389309387232664613430731104442426668",
  "newAuthClaimMtp": [
    "0",
    "624233278507428878357699085848690664404693305135111460161897996527773905329",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0"
  ],
  "newClaimsTreeRoot": "21518774797285335926190213076201354775305473634691721635698084253559224542740",
  "newRevTreeRoot": "0",
  "newRootsTreeRoot": "20276769201543314617493725112370284588843742575818718905960864594995706575389"
}

**Comment by sanketsaagar** [comment]
Hi @jjhbk , Please elaborate more on which part of the tutorial you have followed.

**Comment by sanketsaagar** [comment]
Hi @jjhbk, Didn't hear back from you. Did your issue resolve?
