### ISSUE TITLE
Scanning QR Code

### ISSUE THREAD

**Issue by dominichackett** [0xPolygonID/tutorial-examples#2]
The scanning of the QR code for this tutorial doesn't work.   I scanned the QR code from the documentation and it doesn't move past the authentication page.

**Comment by enricobottazzi** [comment]
Can you provide more details on that and the query that you are designing?

**Comment by sanketsaagar** [comment]
Hi @dominichackett , Can you please let us know if your issue is resolved or not?

**Comment by vmidyllic** [comment]
closed due to the no information from issue creator.
