### ISSUE TITLE
On behalf of the EIP editors, I apologize ahead of time for the inconvenience, but we are in the process of separating the EIPs and ERCs. As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at github.com/ethereum/ercs. Thank you.

### ISSUE THREAD

**Issue by Pandapsy** [0xPolygonID/tutorial-examples#37]
On behalf of the EIP editors, I apologize ahead of time for the inconvenience, but we are in the process of separating the EIPs and ERCs. As this is a PR to create / modify an ERC, I will kindly ask you to redirect this to the new repository at github.com/ethereum/ercs. Thank you.

\- @lightclient 

_Originally posted by @Pandapip1 in https://github.com/ethereum/EIPs/issues/7921_

**Comment by Pandapip1** [comment]
To whoever is operating these stupid spam bots: can you at least have the decency *not* to ping me?
