### ISSUE TITLE
Irrelevant import in on-chain verification

### ISSUE THREAD

**Issue by Amaze09** [0xPolygonID/tutorial-examples#8]
I believe there is an unnecessary import in ZKPVerifier contract at line no. 4  i.e. ERC20.sol
https://github.com/0xPolygonID/tutorial-examples/blob/main/on-chain-verification/contracts/verifiers/ZKPVerifier.sol
Please correct me if I'm missing something.

**Comment by sanketsaagar** [comment]
Hi, @Amaze09  Yes it's an unnecessary import.
