### ISSUE TITLE
add a new project for polygonID

### ISSUE THREAD

**Issue by yogesh0509** [0xPolygonID/tutorial-examples#9]
I want to add a new project to the polygonID on-chain verification. 

Users can submit their government Identity number on-chain and we will send it to [https://api-staging.polygonid.com/v1/issuers/${issuer}/schemas/${schema}/offers](url) via an oracle network to generate the claim that users can scan via their polygonID app.

Instead of calling setZKPRequest off-chain in the deploy script, we can call it on-chain. Here I am using the **IN** operator query. The value key of the query will contain an array containing all the verified IDs thus issuing erc1155 token.

Should I open a pull request for this project?

**Comment by yogesh0509** [comment]
Sure, I will make the necessary changes and request a PR. Since the polygonID docs have changed a lot since the last time I used it, I will update my project accordingly.

**Comment by yogesh0509** [comment]
Hi @sanketsaagar I am working on the repository and am close to requesting a pr. 
Should I directly push a new branch to the [repository](https://github.com/0xPolygonID/contracts) or open an issue first.
Also is there any particular naming convention that I should follow for branches?

**Comment by sanketsaagar** [comment]
Hi @yogesh0509, You can open an issue, and after getting approval you can request for PR.

**Comment by yogesh0509** [comment]
Sure, 
I am trying to mint an erc1155 token once the user has their identity in the polygon wallet app. Also the `setZKPRequest` will be called on-chain. Here is the complete workflow -

* There are 3 types of tokens numbered 0, 1, 2.
* All the users will need to whitelist with us by calling the `whitelistUserId` function. 
* The user calls the function `purchaseProperty(uint64 tokenId)` sending in the type of token they want to purchase. This function will call `set_TRANSFER_REQUEST_ID(tokenId)` and `setZKPRequest`.
* Now any user with the claim who has also whitelisted with us can claim the token by scanning the QR code generated.

All the necessary parameter for calling setZKPRequest is stored on-chain during contract deployment.
Feel free to ask anything else!!

**Comment by sanketsaagar** [comment]
Hi @yogesh0509 , Feel free to raise a PR. There is no official naming convention yet.

**Comment by yogesh0509** [comment]
Thank you, I will raise a pr in a couple of days. Should I also include a readme.md file.

**Comment by sanketsaagar** [comment]
It's on you @yogesh0509, If you want to include a readme then you can.

**Comment by yogesh0509** [comment]
Okay

**Comment by yogesh0509** [comment]
I am ready with my pull request. Just to confirm, I have to open a PR [https://github.com/0xPolygonID/contracts](https://github.com/0xPolygonID/contracts) here and there is no need to create an issue.
